services:
  read-aloud-mcp:
    build: .
    ports:
      - "8000:8000"
    volumes:
      # Mount audio outputs for persistence (optional)
      - ./audio_outputs:/app/audio_outputs
      # Mount PulseAudio socket for audio playback (optional)
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - /run/user/1000/pulse:/tmp/pulse:ro
    environment:
      - DISPLAY=${DISPLAY}
      - PULSE_SERVER=unix:/tmp/pulse/native
    network_mode: host
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Alternative service for stdio mode (for development)
  read-aloud-mcp-stdio:
    build: .
    command: ["uv", "run", "read-aloud-mcp"]
    volumes:
      - ./audio_outputs:/app/audio_outputs
    stdin_open: true
    tty: true
    profiles:
      - stdio
